### PR TITLE
Pagination added to other tables as well

### LINKED ISSUE #63: Paginate All Currently Existing Categories.
Pagination is done in the "All Questions" Category already. You need to do the same for the rest of the categories.

### PR DESCRIPTION
**Pull request by kunal2812**
Fixes #63 
Please review.

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
@kunal2812 Submit the PR link from your Active Issues from http://contrihub21.herokuapp.com/. Only after that it will be evaluated.

**Comment by kunal2812** [comment]
> @kunal2812 Submit the PR link from your Active Issues from http://contrihub21.herokuapp.com/. Only after that it will be evaluated.

Sir, heroku was down for maintenance since 10 pm yesterday so couldn't submit from there and now the duration for submission of PR is over.

**Comment by ankitsangwan1999** [comment]
Ok, request for the issue again.

**Comment by ankitsangwan1999** [comment]
@kunal2812 Assigned to you, now u can submit pr link there.

**Comment by kunal2812** [comment]
@ankitsangwan1999 Done.

**Comment by ankitsangwan1999** [comment]
@kunal2812 Checking

**Pull request merged**
