### PR TITLE
Button to pick a Random Problem currently chosen Category

### PR DESCRIPTION
**Pull request by mrpirated**

### CODE REVIEW

**Comment by mrpirated** [comment]
do i need to do the 2nd part for the popup or for all the tables as well

**Comment by ankitsangwan1999** [comment]
> The image is not loading in the icon what should i do

Try to select the icon using inspect(dev-tools) and change the stylings there and see if you can make it visible.

**Comment by mrpirated** [comment]
I am not able to debug this image error

**Comment by ankitsangwan1999** [comment]
@mrpirated Checking

**Pull request merged**
