### PR TITLE
solve issue #15 : Paginate the Table for the "All Questions" Category

### PR DESCRIPTION
**Pull request by dev-lovedeep**
related to issue #15 
changes did:
1.added a pagination component

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Checking Updates

**Comment by ankitsangwan1999** [comment]
Checking

**Comment by dev-lovedeep** [comment]
this pr is related to issue #15

**Comment by dev-lovedeep** [comment]
sir I am facing some problems while solving this issue, I think it will take some time

**Pull request closed without merging**
