### PR TITLE
modified scrollbar and changed its color to neongreen

### LINKED ISSUE #8: Style the Scroll bar
Make the Scroll bar Neon-Green colored(find hex on google) and also change its default styling (Refer to Discord's Scroll bar).

### PR DESCRIPTION
**Pull request by dev-lovedeep**
regarding fixes #8
did the following changes:
1.changed the color to neongreen
2.minor adjustment in border radius,width etc

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Checking

**Comment by ankitsangwan1999** [comment]
Changes Required:-

1. Change the scrollbar width to 10px from 16px.
2. The Scroll is starting from the top but it should start from the first column of the Table.
3. Also Make the Scroll bar background transparent, only the scrollbar-thumb should be neon green

**Comment by dev-lovedeep** [comment]
i have done the required changes. please have a look! :smile:

**Comment by ankitsangwan1999** [comment]
Checking

**Comment by ankitsangwan1999** [comment]
Remember, You will be judged using code quality as well not just Points.

**Pull request merged**
