### PR TITLE
Reloads the Application when clicked on logo

### LINKED ISSUE #7: Reload the Application when clicking on logo.
Reload the Application when clicking on the "LEETSOLVE" text in the top-left corner.

### PR DESCRIPTION
**Pull request by NeerajChatterjee**
fixed #7

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Functionality Works fine.

Changes Required:-
1. style the span containing the LEETSOLVE text to have a pointer on hovering. You may use {cursor: pointer} styling for that.
2. Use Comments like why false is passed to window.reload()

**Comment by NeerajChatterjee** [comment]
Sure Sir. Working on it.

**Comment by NeerajChatterjee** [comment]
Sir, I did my 2nd commit namely: Added comments and styled cursor. It includes the changes that were required.

**Comment by ankitsangwan1999** [comment]
Bro, npm start se application hi nhi chal rha. Blank Screen aa ja rhi. Fix kro ise aur merge kar lena upstream(ContriHub/Leetsolve vali rep) se phle taki merge conflicts resolve kr lo tum phle hi.

**Comment by ankitsangwan1999** [comment]
Resolving Conflicts.

**Pull request merged**
