### PR TITLE
Restrict window size to 300x400  fixes#2

### LINKED ISSUE #2: Set default window size
Make the App open in full Window size(not Full Screen) by default.

### PR DESCRIPTION
**Pull request by MrRobot2025**
hello sir 
now sir the default size now is 1000x800  when the app opens and now the size is restricted to 300x400. fixes #2
also, I renamed the navbar to header everywhere fixes#4

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Checking

**Comment by metakunal** [comment]
Yes Sir, tested everything in the local environment, everything is working
good.

**Comment by ankitsangwan1999** [comment]
Checking

**Comment by ankitsangwan1999** [comment]
Made 600x600. Looks fine now. Merging This.

**Pull request merged**
