### PR TITLE
Virtual contest implemented

### LINKED ISSUE #19: Virtual Contest of 2-5 Problems from All Questions List
Users should be able to create a Virtual Contest of 2-5 Problems from All Questions List which are free to submit and not submitted already. Basically, Create a table with each row having a Problem Name and + button to add to the Virtual Contest.

**Note:** 
1. This list should not contain the Question already done by the Current User. As soon as the user clicks start Virtual Contest. It should redirect to a Page showing the live status(AC/Non-AC) of the Problems of the Virtual Contest. Live here means that the status should be fetched via an AJAX request.
2. If you want to implement it in another way(should not be costly) you are free to do so.

### PR DESCRIPTION
**Pull request by prbhatter**
Fixes #19 
The questions status will be updated live.(Please wait for a few seconds(atmost 15 sec) to see the updated status)
The selected questions in Virtual Contest will appear at first so that user can easily remove them.
Contest will continue even if one switches to different tabs(like all questions, accepted etc.)

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Nice work so far.
Some changes required:-
1. Screenshot from 2021-10-29 23-33-09 

Styling of "Cross" icon is not Good.

2. Also the styling of the table which contains the currently selected question should be changed, to make it look a bit different from the one from where we are selecting the questions.   
3. As you are fetching the status of all the question every 15 seconds, so implementing it using Ajax is inefficient. What you need to do is have a "Reload Question Status" button to fetch the newest status.
4. Also As the user click on End Virtual Contest, The final status of questions should be fetched and summary of the Contest should be shown in a pop-up modal with how many easy/med/hard questions were solved etc.

**Comment by prbhatter** [comment]
Will do sir.

**Comment by ankitsangwan1999** [comment]
@prbhatter Updates?

**Comment by prbhatter** [comment]
About to complete.
I have also added the timer for Virtual Contest.
Only the different display of selected questions of Virtual Contest is left.

**Comment by prbhatter** [comment]
Done sir. Please check.

**Comment by ankitsangwan1999** [comment]
@prbhatter checking

**Comment by ankitsangwan1999** [comment]
> I have also added the timer for Virtual Contest.

You are supposed to implement that in a separate PR. This PR should not have progress related to that issue. So, make the necessary Changes.

PS: In issue #20, users should set the time for themselves. For further clarifications you can comment on issue itself i.e. [here](https://github.com/ContriHUB/LeetSolve/issues/20)

**Comment by ankitsangwan1999** [comment]
Further Changes:- 
1. When Fetching Status, Show a Loading Indicator and if the request fail/timeout it should show modal/toast saying "Fetching Status Failed", and if the status is updated successfully, it should say "Status Updated Successfully". Currently if the request is timed out then whole page is reloaded and that gif is shown, which should not happen.

**Comment by ankitsangwan1999** [comment]
@prbhatter Inform here once all the changes are done.

**Comment by prbhatter** [comment]
All the changes are done. Please check.

**Comment by ankitsangwan1999** [comment]
@prbhatter Checking Now.

**Comment by ankitsangwan1999** [comment]
Screenshot from 2021-11-02 18-12-27

Summary shown is not correct. It showed 0 Easy question solved, even when I solved one. Although It fetched the status correctly but summary did not handle it after clicking on "End Virtual Contest".

**Comment by prbhatter** [comment]
Solved the issue, sir. Please check.

**Pull request merged**
